language: ruby

rvm:
  - 2.1.1

# TODO: fix the intsall.
# It appears that haml deps are not beings installed:
# it's as if the cd haml had no effect.
install:
  - bundle install
  - cd haml     && bundle install && cd ..
  - cd capybara && bundle install && cd ..

script:
  - bundle exec rake
  - cd haml     && bundle exec rake && cd ..
  - cd capybara && bundle exec rake && cd ..
