task :default do
  require_relative 'main'

  # TODO Run all files that end in `_spec.rb` under `./spec`.
  #begin
    #require 'rspec/core/rake_task'
    #RSpec::Core::RakeTask.new(:spec)
  #rescue LoadError
  #end
end
