task :default do
  # Same as running `rspec` with command given options.
  require 'rspec'
  #RSpec::Core::Runner.run(['main.rb'])
  #RSpec::Core::Runner.run(['spec'])

  # TODO Run all files that end in `_spec.rb` under `./spec`.
  #begin
    #require 'rspec/core/rake_task'
    #RSpec::Core::RakeTask.new(:spec)
  #rescue LoadError
  #end
end
